# Generated by Django 3.2.4 on 2021-06-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='R. Humidity', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='%', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='Vaisala HMP155', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'humidity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Precipitaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Precipitaion', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='mm', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='TB3', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'precipitaion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Air Pressure', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='Pa', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='RM Young 61302V', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pressure',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolarRadiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Solar Rad.', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='W/m^2', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='Kipp & Zonen SP Lite 2', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solrad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Temperature', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='C', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='Vaisala HMP155', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'temperature',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WindDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Wind Dir.', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='Wind Monitor 05305', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'winddir',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hour_class', models.IntegerField()),
                ('is_rainy', models.IntegerField()),
                ('status', models.CharField(default='Good', max_length=50)),
                ('pred_condition', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Wind Speed', max_length=50, null=True)),
                ('unit', models.CharField(blank=True, default='m/s', max_length=50, null=True)),
                ('sensor', models.CharField(blank=True, default='Wind Monitor 05305', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'windspeed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AwsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awsTime', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.precipitaion')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pressure')),
                ('rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.humidity')),
                ('solrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.solarradiation')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.temperature')),
                ('winddir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.winddir')),
                ('windspeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.windspeed')),
            ],
            options={
                'db_table': 'aws_data',
                'managed': True,
            },
        ),
    ]
